### PR TITLE
修复错误的格式化带有中文的 url

### LINKED ISSUE #3: 会对url中的中文也进行格式化，希望升级
image

### PR DESCRIPTION
**Pull request by Cansiny0320**
fix #3

### CODE REVIEW

**Comment by Cansiny0320** [comment]
有时间看看吗 @twocucao

**Comment by hylarucoder** [comment]
@Cansiny0320 多谢, 我稍后发布一下新版本

**Comment by hylarucoder** [comment]
@Cansiny0320 thanks again, i've published version 0.2.2 for your fix

some edge cases still need to be taken into consideration, e.g

image

and imo https://github.com/huacnlee/autocorrect will be a much better alternative to this extension.

**Comment by Cansiny0320** [comment]
> @Cansiny0320 thanks again, i've published version 0.2.2 for your fix
> 
> some edge cases still need to be taken into consideration, e.g
> 
> image
> 
> and imo https://github.com/huacnlee/autocorrect will be a much better alternative to this extension.

ok! thank you

**Pull request merged**
